language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: a3+c+dt3c2FZFAMq7z/U06XiXpRKRgS6QxhtiW8S0R1er7k+PXhSXtFKRfcrq4YYLxBn3wpR+ACD4p/bH/+uRFc4usvRkqf26So7dCeahBcoNgpsKENjhM+fbvVC3TYQpcNcufsdqGmNrpO9yHsDNNNd6GYx9Xt5ldou1U+d5JEbbk9qbsjcXo44pCfGwj0I0nVI9ytD+30/oU1IKgwP6AcvH5Ek8DUyjSoNiRqkB9UiUThyzkKgvGd0fqKUr9d0Cdgjl2RHPHO783wnJ9DPKBd75ZPI1J9OUtQ0cv9v2D40g2+Eu66HIx71O84g6F3L6K5ccfcUvApksFpHYMGimorTCASIL8F3BBWx2RbxZfBjWfozYYoO/HH6B3Jk8l7xnr1Ex4EzVAqwYVS+LUNqYmASyFcDZlmYwiRZaOmo/tJTmgsB4KQiLuV9b9Mtc7TzYZJK+L+8FI9VDaQvQUmNkPqTVMp1blfTWWNr7SUnlGxSEQjWpT7anZNgovU1cVcNjKxpUkcuFQuzjc+6s7+PNEE5AocOLv7wTUXEc6UKFJzYQlrux7Qt9wWzXre3llFVCfBL32/Zv04Bo1GuRIXl0YZEI6K3r7niGvZtJ4G4zAVT4voz0lZa+sdSFBTHUxAbGUYRufaZ91+KnyT5UbkNY66E/AIV6dKr5lnG+FGUaSQ=
  file:
    - "nlcst-normalize.js"
    - "nlcst-normalize.min.js"
  on:
    tags: true
