language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RyZsCRMwN6TGUEaauZ8+ZTJosoZmn8aiArXfnTRoD8BdVOON8g4v/TlswMk/1Nhtj79opyqzzVlQ15dr6sl3KDf6EUTKOSSyCoz0b8vLXAqOhVEJDFT/CKcjUO1LdosUiJBYhEmlWjML6Rzf/A5U4OOd+4UT/X9AfG13W0SH1Ia9gqK3MRU/TWAjo4Dag+6GwZ9w0ymgsPu6AxQu0AJh/3F8ZFwWsUgy9zsLQRmOM+Ad2zeJBIkL3JpBDr4XddbM1rzoX8sXfQ83hNPy32fgP+dX9UFrB9T8sJEq7ExJFeFLyQfoEgYOSoVuqE5GFJ0uAZgn6KuRn59dm/jrh4JLT3uAvpA2USRNsW6FM+eThrB6AyR2qBJ+xp64unlusB+p/eurQ4vyI+EfKXAQBgU2eEZKHVnxxCRkzIZ9NrC4UVCQAReAS006neH3+V8WfTwn4KBeyJOkqQTN3Bu7sjE7w6stBKnmonm4NjtmITWbKf/Q8rrLEkbnTy3DBqWHcS0NHDPaArmNWG3C2U0Rd2nLogWNthIlUyxq6/jlgPdkSfuk5s1BCfMWDglFCAqd7diHREcQhvRT1OWkk+2VJx2U/ZvT7xlv8Mq4jUNhSzCod4BQvMUAgvzfFJd376jPOdeUVxqY63LV0tm1zH3owvYjESsdb11Az5SNFBch25+VTYI=
  file:
    - 'nlcst-normalize.js'
    - 'nlcst-normalize.min.js'
  on:
    tags: true
